In [1]:
import numpy as np

In [2]:
ndarray = np.arange(1,10)

## 1D array

In [3]:
ndarray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2D array

In [10]:
ndarray1 = np.arange(2,20).reshape(3,6)

In [11]:
ndarray1

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

## 3d array

In [13]:
ndarray2 = np.arange(2,20).reshape(2,3,3)

In [14]:
ndarray2

array([[[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])